services:
  coordinator:
    container_name: coordinator
    image: citusdata/citus
    restart: always
    depends_on:
      worker-101:
        condition: service_healthy
      worker-102:
        condition: service_healthy
    volumes:
      - ./coordinator/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - citus
    environment:
      POSTGRES_PASSWORD: example
  worker-101:
    container_name: worker-101
    image: citusdata/citus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    networks:
      - citus
    environment:
      POSTGRES_PASSWORD: example
  worker-102:
    container_name: worker-102
    image: citusdata/citus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    networks:
      - citus
    environment:
      POSTGRES_PASSWORD: example
networks:
  citus:
    name: citus
